apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connectedflow-ingress
  namespace: connectedflow-core
  labels:
    app.kubernetes.io/part-of: connectedflow
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - connectedflow.example.com
      secretName: connectedflow-tls
  rules:
    - host: connectedflow.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
