apiVersion: v1
kind: Namespace
metadata:
  name: connectedflow-core
  labels:
    app.kubernetes.io/part-of: connectedflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: connectedflow-data
  labels:
    app.kubernetes.io/part-of: connectedflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: connectedflow-integration
  labels:
    app.kubernetes.io/part-of: connectedflow
